### ISSUE TITLE
Support `spec.filter.limit` > 20

### ISSUE THREAD

**Issue by vadasambar** [vadasambar/hnews#1]
## Problem
- As of now, `spec.filter.limit` > 20 cannot be specified. You will get a validation error. This is to prevent the controller from processing too deep i.e., making too many requests to fill the the 20 articles which match the filter. This is because, it'd take time and lead to a lot of requests to the api. 

## Solutions
- We can't really prevent the load on the API right now but we might be able to reduce the time using goroutines

## TODO
- [ ] Evaluate goroutines for enabling `spec.filter.limit` > 20
- [ ] If it seems feasible, make the change and raise a PR
- [ ] If it doesn't comment in this issue and close it (wait for the upstream api to fix the issue i.e., give us a better api)

## Definition of DONE
- I should be able to specify `spec.filter.limit` = 20
